name: Rust

on:
  workflow_dispatch 

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Rust
      run: |
        cd backend
        cargo build  --release
    - name: Build Svelte
      run: |
        cd frontend
        yarn
        yarn build
    - name: Copy files
      run: |
        src=$(pwd)
        stage=
        case $RUNNER_OS in
            Linux)
                stage=$(mktemp -d)
                ;;
            macOS)
                stage=$(mktemp -d -t tmp)
                ;;
        esac
        cp target/release/sysit $stage/
        cp -r frontend/build $stage/public
        cd $stage
        RELEASE_VERSION=${GITHUB_REF#refs/tags/}
        ASSET_NAME="$RELEASE_VERSION.tar.gz"
        ASSET_PATH="$src/$ASSET_NAME"
        echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
        tar czf $ASSET_PATH *
        cd $src
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
       files: |
         ${{ env.ASSET_PATH }}
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
